title: Ralf Th. Pietsch
description: Developing with passion
owner: Ralf Th. Pietsch
url_github: https://github.com/ratopi/
url_comments: https://github.com/ratopi/ratopi.github.io/issues
permalink: /:year/:title.html
